<li><a href="<?php echo $this->url(array('controller' => 'index',       'action' => 'index'), 'default', true); ?>">Home<span>Home</span></a></li>
<li><a href="<?php echo $this->url(array('controller' => 'news',        'action' => 'index'), 'default', true); ?>">News<span>News</span></a></li>
<li><a href="<?php echo $this->url(array('controller' => 'image',       'action' => 'index'), 'default', true); ?>">Images<span>Images</span></a></li>
<li><a href="<?php echo $this->url(array('controller' => 'admintools',  'action' => 'index'), 'default', true); ?>">Tools<span>Tools</span></a></li>
